-- MODERN BUSINESS MUM - AI OPERATIONS TEAM DATABASE SCHEMA
-- Tables for managing client subscriptions, AI interactions, and workspace data

-- Clients subscribed to Modern Business Mum AI Ops Team
CREATE TABLE IF NOT EXISTS mbm_clients (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  business_name TEXT NOT NULL,
  contact_email TEXT NOT NULL UNIQUE,
  monthly_revenue TEXT,
  team_size INTEGER,
  biggest_challenge TEXT,
  subscription_status TEXT DEFAULT 'trial', -- trial, active, cancelled
  subscription_start_date TIMESTAMP DEFAULT NOW(),
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- AI interactions and memory
CREATE TABLE IF NOT EXISTS mbm_ai_interactions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES mbm_clients(id),
  agent_type TEXT NOT NULL, -- chief_of_staff, project_manager, analyst
  request TEXT NOT NULL,
  response TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Client SOPs and documentation
CREATE TABLE IF NOT EXISTS mbm_client_sops (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES mbm_clients(id),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT, -- operations, sales, marketing, etc
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(client_id, title)
);

-- Workspace items to be organized
CREATE TABLE IF NOT EXISTS mbm_workspace_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES mbm_clients(id),
  title TEXT NOT NULL,
  description TEXT,
  type TEXT, -- project, task, document, etc
  category TEXT,
  tags TEXT[],
  priority TEXT, -- high, medium, low
  organized BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Project tracking
CREATE TABLE IF NOT EXISTS mbm_client_projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES mbm_clients(id),
  name TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'active', -- active, on_hold, completed
  priority TEXT DEFAULT 'medium',
  due_date DATE,
  owner TEXT,
  progress INTEGER DEFAULT 0, -- 0-100
  blockers TEXT[],
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Weekly reports generated by AI Analyst
CREATE TABLE IF NOT EXISTS mbm_weekly_reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  client_id UUID REFERENCES mbm_clients(id),
  week_of DATE NOT NULL,
  report_content TEXT NOT NULL,
  key_metrics JSONB,
  insights TEXT[],
  recommendations TEXT[],
  created_at TIMESTAMP DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_mbm_ai_interactions_client ON mbm_ai_interactions(client_id);
CREATE INDEX IF NOT EXISTS idx_mbm_ai_interactions_created ON mbm_ai_interactions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mbm_client_sops_client ON mbm_client_sops(client_id);
CREATE INDEX IF NOT EXISTS idx_mbm_workspace_items_client ON mbm_workspace_items(client_id);
CREATE INDEX IF NOT EXISTS idx_mbm_workspace_items_organized ON mbm_workspace_items(organized);
CREATE INDEX IF NOT EXISTS idx_mbm_client_projects_client ON mbm_client_projects(client_id);
CREATE INDEX IF NOT EXISTS idx_mbm_client_projects_status ON mbm_client_projects(status);
CREATE INDEX IF NOT EXISTS idx_mbm_weekly_reports_client ON mbm_weekly_reports(client_id);
